import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

import { faFacebookF } from "@fortawesome/free-brands-svg-icons";
import {
  faSearch,
  faUserAlt,
  faBell,
  faEllipsisV,
  faEllipsisH,
  faSave,
  faHistory,
  faRandom,
  faAlignJustify,
  faExclamationTriangle,
  faBellSlash,
  faCamera,
  faCaretRight,
  faGlobe,
  faPaperPlane,
  faShare,
  faSmile,
  faComment,
} from "@fortawesome/free-solid-svg-icons";
import {
  faThumbsUp,
  faComment as faCommentRegular,
  faShareSquare,
  faBookmark,
  faBell as faBellRegular,
  faEyeSlash,
  faClock,
  faFileCode,
  faTimesCircle,
  faFlag,
} from "@fortawesome/free-regular-svg-icons";

export {
  FontAwesomeIcon,
  faFacebookF,
  faSearch,
  faUserAlt,
  faComment,
  faBell,
  faEllipsisV,
  faEllipsisH,
  faSave,
  faHistory,
  faRandom,
  faAlignJustify,
  faEyeSlash,
  faExclamationTriangle,
  faBellSlash,
  faClock,
  faThumbsUp,
  faCommentRegular,
  faShareSquare,
  faTimesCircle,
  faCamera,
  faCaretRight,
  faGlobe,
  faPaperPlane,
  faShare,
  faSmile,
  faBookmark,
  faBellRegular,
  faFileCode,
  faFlag,
};
